### ISSUE TITLE
Chignolin forces shape mismatch

### ISSUE THREAD

**Issue by tkreiman** [torchmd/torchmd-protein-thermodynamics#20]
When downloading the data, chignolin_ca_forces.npy has shape (1868861, 97, 3) while the delta forces has (1868861, 10, 3) which makes sense since there are 10 amino acids. What are the 97 corresponding to / how do I recover the ground truth QM forces?

**Comment by AdriaPerezCulubret** [comment]
Careful! The "ground thruth" forces are not QM, they come from classical MM forcefield simulations (CHARM22*).

Just checked and the provided forces for chignolin are wrong, since I'm providing all-atom forces and not only the CA atoms forces. I'll fix it so that the shape in chignolin_ca_forces.npy is (1868861, 10, 3).

**Comment by AdriaPerezCulubret** [comment]
Uploaded the correct array now, link corrected!

**Comment by tkreiman** [comment]
Thank you!
