### ISSUE TITLE
Questions about units and data

### ISSUE THREAD

**Issue by tkreiman** [torchmd/torchmd-protein-thermodynamics#22]
Hello, I had 2 quick questions:

1. What are the units of the target forces / delta forces and thus what are the units of the train/val/test losses in the training curves in figure 3 of the paper?
2. I see that you released a dataset of trajectories from the mutant proteins, but are the forces for those trajectories also available?

Thanks for the help!

**Comment by Jingdan-Chen** [comment]
I think you may find the ans to Q1 in closed issues.
Coordinates are in Å and forces are in kcal/mol/Å. :)

**Comment by AdriaPerezCulubret** [comment]
1. Exactly, forces (and deltaforces) are in kcal/mol/Å. Units for train/val/test are the same. (I guess you meant figure S13, and not 3)
2. No, there are no all-atom forces for the mutant trajectories, since those are coarse-grained trajectories. There's no all-atom MD simulations of the mutants, we directly simulated them with our multi-protein coarse-grained model to test its ability to generalize outside of the training-set of 12 proteins.
